name = "railway_layer_model"
uuid = "408ab8f0-951a-4262-85b8-7f78191ce244"
authors = ["Martin Scheidt <m.scheidt@tu-braunschweig.de>"]
version = "0.1.0"

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
JSONSchema = "7d188eb4-7ad8-530c-ae41-71a32a6d4692"
YAML = "ddb6d928-2868-570f-bddf-ab3f9cf99eb6"

[compat]
DataFrames = "^1.4"
JSONSchema = "^1"
YAML = "^0.4"
julia = "^1.6"
