%YAML 1.2
---
base:
  name: "Example Infrastructure"
  id: base
  stations:
    - id: XWN
      name: Wenden
      plot_coord: [0.0,0.0]
      pos:
        - line: "9721"
          milage: 9.1
    - id: XR
      name: Rebenau
      plot_coord: [2.0,0.0]
      pos:
        - line: "9721"
          milage: 16.3
        - line: "9724"
          milage: 0.561
    - id: XOG
      name: Okerbach Gbf
      plot_coord: [4.5,-0.5]
      pos:
        - line: "9721"
          milage: 26.3
    - id: XO
      name: Okerbach Pbf
      plot_coord: [5.5,-0.5]
      pos:
        - line: "9721"
          milage: 27.2
    - id: XBU
      name: Abzweig Bülten
      plot_coord: [8.0,0.0]
      pos:
        - line: "9721"
          milage: 32.1
        - line: "9724"
          milage: 18.9
    - id: XSZ
      name: Schleinitz
      plot_coord: [10.0,0.0]
      pos:
        - line: "9721"
          milage: 36.0
    - id: XSBG
      name: Schlossberg
      plot_coord: [13.0,0.0]
      pos:
        - line: "9721"
          milage: 42.8
    - id: XM
      name: Mittelstadt
      plot_coord: [2.0,1.0]
      pos:
        - line: "9344"
          milage: 5.5
    - id: XPD
      name: Pockelsdorf
      plot_coord: [5.0,0.5]
      pos:
        - line: "9724"
          milage: 9.8
        - line: "9344"
          milage: 9.7
  relations:
    # Wenden Schlossberg via Okerbach (9721)
    - source: XWN
      target: XR
      length: 7.2
    - source: XR
      target: XOG
      length: 10.0
    - source: XOG
      target: XO
      length: 0.9
    - source: XO
      target: XBU
      length: 4.9
    - source: XBU
      target: XSZ
      length: 3.9
    - source: XSZ
      target: XSBG
      length: 6.8
    # Rebenau Buelten via Pockelsdorf (9724)
    - source: XR
      target: XPD
      length: 9.8
    - source: XPD
      target: XBU
      length: 9.1
    # Mittelstadt Pockelsdorf (9344)
    - source: XM
      target: XPD
      length: 9.5
  lines:
    - name: Wenden Schlossberg via Okerbach
      id: "9721"
    - name: Rebenau Buelten via Pockelsdorf
      id: "9724"
    - name: Mittelstadt Pockelsdorf
      id: "9344"
